# Generated by Django 5.2.13 on 2026-06-25 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Aula')),
                ('ubicacion', models.CharField(help_text='Ej: Edificio 2, Planta Alta', max_length=150, verbose_name='Ubicación')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad de Alumnos')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción/Equipamiento Fijo')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Recurso')),
                ('codigo_inventario', models.CharField(max_length=50, unique=True, verbose_name='Código de Inventario')),
                ('stock_total', models.IntegerField(default=1, verbose_name='Stock Total')),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Está Disponible?')),
            ],
            options={
                'verbose_name': 'Material/Recurso',
                'verbose_name_plural': 'Stock de Materiales',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(verbose_name='Fecha de la Reserva')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Cancelada', 'Cancelada'), ('Finalizada', 'Finalizada')], default='Activa', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.aula')),
                ('materiales', models.ManyToManyField(blank=True, related_name='reservas', to='reservas.material')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_reserva', '-hora_inicio'],
            },
        ),
    ]
