# Generated by Django 5.2.13 on 2026-06-27 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
        ('reservas', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='comision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_aula', to='academia.comision'),
        ),
    ]
