# Generated by Django 5.2.13 on 2026-06-27 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Carrera')),
                ('codigo', models.CharField(help_text='Ej: LSI, MI', max_length=10, unique=True, verbose_name='Código/Sigla')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Materia')),
                ('ano', models.IntegerField(choices=[(1, '1er Año'), (2, '2do Año'), (3, '3er Año'), (4, '4to Año'), (5, '5to Año')], verbose_name='Año de Cursada')),
                ('cuatrimestre', models.IntegerField(choices=[(1, '1er Cuatrimestre'), (2, '2do Cuatrimestre'), (3, 'Anual')], verbose_name='Cuatrimestre')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academia.carrera')),
            ],
            options={
                'unique_together': {('carrera', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Comisión A, Única', max_length=10, verbose_name='Nombre Comisión')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], max_length=10, verbose_name='Día de Cursada')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Inicio Cursada')),
                ('hora_fin', models.TimeField(verbose_name='Hora Fin Cursada')),
                ('alumnos', models.ManyToManyField(blank=True, limit_choices_to={'profile__rol': 'student'}, related_name='comisiones_inscritas', to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(limit_choices_to={'profile__rol': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comisiones_dictadas', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='academia.materia')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
            },
        ),
    ]
